Added Navbar
Raghav888/react-bookstore pull request #1
Opened 2022-03-14 05:39 UTC by Raghav888

2022-03-14 18:08 UTC, tusharkandpal requested changes
Minor suggestion below else is good.

2022-03-14 18:08 UTC, tusharkandpal commented on src/components/shared/navbar/Navbar.js
> +        <a className="mantra-title" href="index.html"> BookStore </a>
You can remove all `a` tags in this component.

2022-03-15 02:40 UTC, Raghav888 commented on src/components/shared/navbar/Navbar.js
> +        <a className="mantra-title" href="index.html"> BookStore </a>
I will remove it, once I create all other components

2022-03-15 04:38 UTC, tusharkandpal commented on src/components/shared/navbar/Navbar.js
> +        <a className="mantra-title" href="index.html"> BookStore </a>
Alright.

2022-03-15 04:39 UTC, tusharkandpal approved these changes
You can go ahead & merge.

2022-03-15 10:21 UTC, mariyasada approved these changes

2022-03-15 10:21 UTC, mariyasada commented on src/components/shared/navbar/Navbar.js
> +    return(
use es6 format

2022-03-15 10:21 UTC, mariyasada commented on src/pages/landing/Home.js
> +    return(
same here

2022-03-15 10:54 UTC, Raghav888 commented on src/components/shared/navbar/Navbar.js
> +    return(
Will do it

2022-03-15 10:54 UTC, Raghav888 commented on src/pages/landing/Home.js
> +    return(
Will do it

2022-03-15 10:54 UTC, merged